### ISSUE TITLE
Would be useful to display total entries before you start to size them

### ISSUE THREAD

**Issue by gingerbeardman** [Ghosty-Tongue/IA-Account-Backup#1]
I have over 1000 items on my account, so it would be good to get some progress of them as they are sized, rather than the progress bar just being for the download. 

Currently you just see identifier after identifier being sized with no end in sight.

Thanks for this tool!

**Comment by Ghosty-Tongue** [comment]
A temporary addition was added for this request until I can figure out the progress bars for the identifiers.

**Comment by Ghosty-Tongue** [comment]
I should have mentioned this in the readme.md, but this was closed source and privately used by me because my original account got banned. Knowing that all my stuff was going to be gone in about a week, I speedran to make the script so I could repost all my items onto an alt, and it worked, lol.

**Comment by gingerbeardman** [comment]
I feel you

Cheers

**Comment by Ghosty-Tongue** [comment]
Progress bars should have been added. I kind of forgot whether I removed them in newer revisions or not.
